apiVersion: apps/v1
kind: Deployment
metadata:
  name: sterling-poc
  labels:
    app: sterling-poc
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sterling-poc
  template:
    metadata:
      labels:
        app: sterling-poc
    spec:
      containers:
        - name: sterling-poc
          image: ${IMAGE_URI}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: GCP_SUBSCRIPTION
              value: projects/gentera-proyects/subscriptions/sterling-bucket-dev-subscription
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/credentials.json
            - name: BUCKET_NAME
              value: sterling-bucket-dev
          volumeMounts:
            - name: gcp-creds
              mountPath: /secrets
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 15
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 15
            failureThreshold: 3
      volumes:
        - name: gcp-creds
          secret:
            secretName: gcp-pubsub-credentials
