apiVersion: v1
kind: Service
metadata:
  name: sterling-poc-service
  labels:
    app: sterling-poc
spec:
  type: LoadBalancer
  selector:
    app: sterling-poc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
